import { makeStyles, tokens } from '@fluentui/react-components';

export const useCertNodeStyles = makeStyles({
  root: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: tokens.spacingVerticalM,
    position: 'relative',
    width: '400px',
    height: '230px',
    touchAction: 'manipulation',
  },
  info: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    padding: tokens.spacingVerticalL,
    backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    borderRadius: tokens.borderRadiusLarge,
    boxShadow: tokens.shadow2,
    cursor: 'pointer',
    transitionProperty: 'all',
    transitionDuration: 'var(--duration-normal)',
    transitionTimingFunction: 'var(--curve-easy-ease)',
    minWidth: 0,
    position: 'relative',
    overflow: 'hidden',
    zIndex: 6,
    height: '100%',
    '::after': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: 'linear-gradient(135deg, color-mix(in srgb, var(--cert-node-color) 10%, transparent) 0%, transparent 100%)',
      opacity: 0.8,
      zIndex: -1,
      pointerEvents: 'none',
      transitionProperty: 'opacity',
      transitionDuration: 'var(--duration-fast)',
      transitionTimingFunction: 'var(--curve-easy-ease)',
    },
    ':hover': {
      transform: 'translateY(-2px)',
      boxShadow: `${tokens.shadow8}, 0 0 16px color-mix(in srgb, var(--cert-node-color) 15%, transparent)`,
      borderColor: 'color-mix(in srgb, var(--cert-node-color) 50%, var(--colorNeutralStroke1))',
    },
    ':active': {
      transform: 'scale(0.98)',
    },
    ':focus-visible': {
      outline: '2px solid var(--cert-node-color)',
      outlineOffset: '2px',
    },
  },
  infoNotStartedLocked: {
    opacity: 0.6,
    filter: 'grayscale(0.6)',
    ':hover': {
      opacity: 0.9,
      filter: 'grayscale(0.2)',
    },
  },
  infoUnlocked: {
    opacity: 1,
    borderColor: 'color-mix(in srgb, var(--cert-node-color) 80%, transparent)',
    boxShadow: '0 0 12px color-mix(in srgb, var(--cert-node-color) 20%, transparent)',
    ':hover': {
      borderColor: 'var(--cert-node-color)',
      boxShadow: '0 4px 16px color-mix(in srgb, var(--cert-node-color) 30%, transparent)',
    },
  },
  infoCompleted: {
    borderColor: 'color-mix(in srgb, var(--cert-node-color) 60%, transparent)',
    boxShadow: '0 0 8px color-mix(in srgb, var(--cert-node-color) 30%, transparent), 0 0 24px color-mix(in srgb, var(--cert-node-color) 15%, transparent), 0 0 48px color-mix(in srgb, var(--cert-node-color) 5%, transparent)',
  },
  infoIgnored: {
    borderColor: tokens.colorNeutralStroke2,
    boxShadow: tokens.shadow2,
    ':hover': {
      borderColor: tokens.colorNeutralStroke1,
      boxShadow: tokens.shadow4,
      transform: 'translateY(-2px)',
    },
  },
  infoHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: tokens.spacingVerticalS,
  },
  iconTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalM,
    minWidth: 0,
    flex: 1,
  },
  icon: {
    width: '36px',
    height: '36px',
    borderRadius: tokens.borderRadiusMedium,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'color-mix(in srgb, var(--cert-node-color) 12%, var(--colorNeutralBackground3))',
    color: 'var(--cert-node-color)',
    flexShrink: 0,
    overflow: 'hidden',
  },
  iconImage: {
    width: '44px',
    height: '44px',
    backgroundColor: 'transparent !important',
    border: 'none !important',
    borderRadius: 0,
    boxShadow: 'none !important',
    overflow: 'visible',
  },
  iconIgnored: {
    backgroundColor: `${tokens.colorNeutralBackground3} !important`,
    color: `${tokens.colorNeutralForeground3} !important`,
  },
  iconImageIgnored: {
    opacity: 0.55,
    filter: 'grayscale(0.4)',
  },
  badgeImage: {
    width: '100%',
    height: '100%',
    objectFit: 'contain',
    filter: 'drop-shadow(0 2px 4px rgba(0, 0, 0, 0.2))',
    transitionProperty: 'transform',
    transitionDuration: 'var(--duration-fast)',
    transitionTimingFunction: 'var(--curve-easy-ease)',
    ':hover': {
      transform: 'scale(1.05)',
    },
  },
  titleGroup: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '2px',
  },
  badgeStats: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    flexWrap: 'wrap',
  },
  examCode: {
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--fs-caption1)',
    fontWeight: tokens.fontWeightSemibold,
    color: 'var(--cert-node-color)',
  },
  examCodeIgnored: {
    color: tokens.colorNeutralForeground2,
  },
  name: {
    fontSize: tokens.fontSizeBase300,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorNeutralForeground1,
    lineHeight: 1.2,
    margin: 0,
  },
  infoBody: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalS,
    marginBottom: tokens.spacingVerticalM,
  },
  description: {
    fontSize: 'var(--fs-caption1)',
    color: tokens.colorNeutralForeground2,
    lineHeight: 1.4,
    margin: 0,
    display: '-webkit-box',
    WebkitLineClamp: 3,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  infoFooter: {
    marginTop: 'auto',
    display: 'flex',
  },
  actions: {
    display: 'flex',
    gap: tokens.spacingHorizontalS,
    width: '100%',
    alignItems: 'center',
  },
  learnLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    height: '26px',
    fontSize: 'var(--fs-caption2)',
    fontWeight: tokens.fontWeightSemibold,
    padding: '0 8px',
    borderRadius: tokens.borderRadiusSmall,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground2,
    color: tokens.colorNeutralForeground2,
    textDecorationLine: 'none',
    transitionProperty: 'all',
    transitionDuration: 'var(--duration-fast)',
    transitionTimingFunction: 'var(--curve-easy-ease)',
    whiteSpace: 'nowrap',
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
      borderColor: tokens.colorNeutralStroke1,
      color: tokens.colorNeutralForeground1,
    },
    ':active': {
      transform: 'scale(0.96)',
    },
  },
  statusToggle: {
    display: 'inline-flex',
    alignItems: 'center',
    backgroundColor: tokens.colorNeutralBackground2,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: tokens.borderRadiusMedium,
    padding: '2px',
    gap: '3px',
    '@media (pointer: coarse)': {
      padding: '3px',
      gap: '4px',
    },
  },
  toggleBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '26px',
    height: '24px',
    border: 'none',
    backgroundColor: 'transparent',
    borderRadius: tokens.borderRadiusSmall,
    color: tokens.colorNeutralForeground2,
    cursor: 'pointer',
    touchAction: 'manipulation',
    transitionProperty: 'all',
    transitionDuration: 'var(--duration-fast)',
    transitionTimingFunction: 'var(--curve-easy-ease)',
    ':hover': {
      backgroundColor: tokens.colorSubtleBackgroundHover,
      color: tokens.colorNeutralForeground1,
    },
    ':active': {
      transform: 'scale(0.92)',
    },
    '@media (pointer: coarse)': {
      width: '30px',
      height: '28px',
    },
  },
  toggleBtnActiveNotStarted: {
    boxShadow: tokens.shadow2,
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  toggleBtnActiveInProgress: {
    boxShadow: tokens.shadow2,
    backgroundColor: 'var(--badge-inprogress-bg)',
    color: 'var(--badge-inprogress-fg)',
    border: '1px solid var(--badge-inprogress-border)',
  },
  toggleBtnActivePassed: {
    boxShadow: tokens.shadow2,
    backgroundColor: 'var(--badge-completed-bg)',
    color: 'var(--badge-completed-fg)',
    border: '1px solid var(--badge-completed-border)',
  },
  toggleBtnActiveRenewal: {
    boxShadow: tokens.shadow2,
    backgroundColor: 'color-mix(in srgb, var(--line-security) 10%, transparent)',
    color: 'var(--line-security)',
    border: '1px solid color-mix(in srgb, var(--line-security) 40%, transparent)',
  },
  trackBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '32px',
    height: '32px',
    borderRadius: tokens.borderRadiusSmall,
    border: '1px solid transparent',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    touchAction: 'manipulation',
    transitionProperty: 'all',
    transitionDuration: 'var(--duration-fast)',
    transitionTimingFunction: 'var(--curve-easy-ease)',
    zIndex: 2,
    flexShrink: 0,
    padding: 0,
    ':active': {
      transform: 'scale(0.92)',
    },
    ':disabled': {
      cursor: 'not-allowed',
      opacity: 0.4,
    },
    '@media (pointer: coarse)': {
      width: '36px',
      height: '36px',
    },
  },
  trackBtnTracked: {
    backgroundColor: 'color-mix(in srgb, var(--cert-node-color) 12%, transparent)',
    borderColor: 'color-mix(in srgb, var(--cert-node-color) 30%, transparent)',
    color: 'var(--cert-node-color)',
    ':hover': {
      backgroundColor: 'color-mix(in srgb, var(--cert-node-color) 22%, transparent)',
      borderColor: 'var(--cert-node-color)',
      transform: 'scale(1.05)',
    },
  },
  trackBtnUntracked: {
    backgroundColor: tokens.colorNeutralBackground2,
    borderColor: tokens.colorNeutralStroke2,
    color: tokens.colorNeutralForeground3,
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
      borderColor: tokens.colorNeutralStroke1,
      color: tokens.colorNeutralForeground1,
      transform: 'scale(1.05)',
    },
  },
});
