import {
  OpenRegular,
  DismissRegular,
  SearchRegular,
  NavigationRegular,
  WeatherSunnyRegular,
  WeatherMoonRegular,
  DesktopRegular,
  ChevronDoubleLeftRegular,
  ChevronDoubleRightRegular,
  ChevronDownRegular,
  CircleRegular,
  CheckmarkCircleRegular,
  ClockRegular,
  ArrowTrendingRegular,
  BookOpenRegular,
  ChevronRightRegular,
  ArrowRightRegular,
  EyeRegular,
  EyeOffRegular,
  TrophyRegular,
  WarningRegular,
  ArrowSwapRegular,
  CalendarRegular,
  ArchiveRegular,
  CheckmarkRegular,
  LinkRegular,
  LocationOffRegular,
  BranchForkRegular,
  ArrowSyncRegular,
  ReOrderDotsVerticalRegular,
  StarRegular,
  ShieldRegular,
  AddCircleRegular,
  MedalRegular,
  SettingsRegular,
  DataBarVerticalRegular,
  CodeRegular,
  PeopleRegular,
  KeyRegular,
  DocumentCheckmarkRegular,
  LayerRegular,
  ShieldErrorRegular,
  MapRegular,
  ListRegular,
  AddRegular,
  SubtractRegular,
  ArrowUpRegular,
  ArrowDownRegular,
  ArrowLeftRegular,
  LockClosedRegular,
  InfoRegular,
  DocumentArrowDownRegular,
  DocumentArrowUpRegular,
  DatabaseRegular,
  BookmarkRegular,
  BookmarkFilled,
  BookmarkOffRegular,
} from '@fluentui/react-icons';

// Microsoft Product Icons (custom SVGs for certification paths)
import {
  AzureIcon,
  AzureAIIcon,
  DataAnalyticsIcon,
  SecurityIcon,
  M365Icon,
  PowerPlatformIcon,
  CopilotIcon,
  DynamicsIcon,
  GitHubIcon,
  ArchiveIcon,
  DashboardIcon,
  AzureDevOpsIcon,
  CareerPathIcon,
  SettingsColorIcon,
  AppliedSkillsIcon,
} from './ProductIcons';

const withSize = (IconComponent) => {
  // eslint-disable-next-line no-unused-vars
  return function WrappedIcon({ size, className, style, strokeWidth: _strokeWidth, ...props }) {
    const defaultSize = 20;
    const finalSize = size || defaultSize;
    // Fluent UI icons use width/height or fontSize. We provide both to be safe.
    const customStyle = { 
      fontSize: finalSize, 
      width: finalSize, 
      height: finalSize, 
      ...style 
    };
    return <IconComponent className={className} style={customStyle} {...props} />;
  };
};

export const IconMap = {
  // ── Microsoft Product Icons (certification paths) ──
  Microsoft: M365Icon,
  Cloud: AzureIcon,
  Brain: AzureAIIcon,
  Database: DataAnalyticsIcon,
  Shield: SecurityIcon,
  Monitor: M365Icon,
  Zap: PowerPlatformIcon,
  Bot: CopilotIcon,
  Briefcase: DynamicsIcon,
  GitHub: GitHubIcon,
  AzureDevOps: AzureDevOpsIcon,
  GitBranch: withSize(BranchForkRegular),
  Archive: ArchiveIcon,
  CareerPath: CareerPathIcon,
  AppliedSkills: AppliedSkillsIcon,

  // ── UI Icons (Fluent UI) ──
  LayoutDashboard: DashboardIcon,
  LayoutGrid: DashboardIcon,
  ExternalLink: withSize(OpenRegular),
  X: withSize(DismissRegular),
  Search: withSize(SearchRegular),
  Menu: withSize(NavigationRegular),
  Sun: withSize(WeatherSunnyRegular),
  Moon: withSize(WeatherMoonRegular),
  Desktop: withSize(DesktopRegular),
  ChevronsLeft: withSize(ChevronDoubleLeftRegular),
  ChevronsRight: withSize(ChevronDoubleRightRegular),
  Circle: withSize(CircleRegular),
  CheckCircle2: withSize(CheckmarkCircleRegular),
  Clock: withSize(ClockRegular),
  TrendingUp: withSize(ArrowTrendingRegular),
  BookOpen: withSize(BookOpenRegular),
  ChevronRight: withSize(ChevronRightRegular),
  ChevronDown: withSize(ChevronDownRegular),
  ArrowRight: withSize(ArrowRightRegular),
  Eye: withSize(EyeRegular),
  EyeOff: withSize(EyeOffRegular),
  Award: withSize(TrophyRegular),
  AlertTriangle: withSize(WarningRegular),
  ArrowRightLeft: withSize(ArrowSwapRegular),
  Calendar: withSize(CalendarRegular),
  ArchiveX: withSize(ArchiveRegular),
  Check: withSize(CheckmarkRegular),
  Link: withSize(LinkRegular),
  MapPinOff: withSize(LocationOffRegular),
  RefreshCw: withSize(ArrowSyncRegular),
  Compass: withSize(MapRegular),
  Map: withSize(MapRegular),
  List: withSize(ListRegular),
  GripVertical: withSize(ReOrderDotsVerticalRegular),
  Star: withSize(StarRegular),
  ShieldIcon: withSize(ShieldRegular),
  PlusCircle: withSize(AddCircleRegular),
  Medal: withSize(MedalRegular),
  Plus: withSize(AddRegular),
  Minus: withSize(SubtractRegular),
  ArrowUp: withSize(ArrowUpRegular),
  ArrowDown: withSize(ArrowDownRegular),
  ArrowLeft: withSize(ArrowLeftRegular),
  Lock: withSize(LockClosedRegular),
  Info: withSize(InfoRegular),
  Download: withSize(DocumentArrowDownRegular),
  Upload: withSize(DocumentArrowUpRegular),
  DatabaseIcon: withSize(DatabaseRegular),
  Bookmark: withSize(BookmarkRegular),
  BookmarkFilled: withSize(BookmarkFilled),
  BookmarkOff: withSize(BookmarkOffRegular),
  
  // New role icons
  Settings: withSize(SettingsRegular),
  BarChart2: withSize(DataBarVerticalRegular),
  Code2: withSize(CodeRegular),
  Users: withSize(PeopleRegular),
  Key: withSize(KeyRegular),
  FileCheck2: withSize(DocumentCheckmarkRegular),
  Layers: withSize(LayerRegular),
  ShieldAlert: withSize(ShieldErrorRegular),
  LineChart: withSize(ArrowTrendingRegular),
  SettingsColor: SettingsColorIcon,
};
